version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/node_modules"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    